"""zotcleanup — scriptable cleanup pipeline for a personal Zotero library."""

from __future__ import annotations

from .cli import Changes, apply_updates, build_parser
from .client import ConfigError, get_client
from .collections import (
    Tree,
    add_items_to_collection,
    all_collections,
    create_collection,
    merge_collection,
    rename_collection,
)
from .helpers import (
    ARXIV_NEW_RE,
    ARXIV_OLD_RE,
    arxiv_enrich_or_demote,
    arxiv_id_from_doi,
    arxiv_id_from_extra,
    arxiv_id_from_url,
    arxiv_paper,
    clean_arxiv_categories,
    compile_canonical_replacer,
    crossref_date,
    crossref_works,
    DBLPThrottled,
    dblp_authors,
    dblp_search,
    fetch_items,
    is_arxiv_placeholder_doi,
    is_researchgate_doi,
    latex_to_unicode,
    norm_title,
    prefetch_arxiv,
    retype,
    split_list,
    strip_bbt_braces,
    strip_extra_lines,
)

__all__ = [
    "get_client",
    "ConfigError",
    "fetch_items",
    "arxiv_enrich_or_demote",
    "arxiv_id_from_url",
    "arxiv_id_from_extra",
    "arxiv_id_from_doi",
    "arxiv_paper",
    "ARXIV_NEW_RE",
    "ARXIV_OLD_RE",
    "prefetch_arxiv",
    "crossref_works",
    "crossref_date",
    "dblp_search",
    "dblp_authors",
    "DBLPThrottled",
    "is_researchgate_doi",
    "is_arxiv_placeholder_doi",
    "split_list",
    "norm_title",
    "clean_arxiv_categories",
    "strip_extra_lines",
    "strip_bbt_braces",
    "latex_to_unicode",
    "compile_canonical_replacer",
    "retype",
    "build_parser",
    "apply_updates",
    "Changes",
    "all_collections",
    "Tree",
    "create_collection",
    "rename_collection",
    "add_items_to_collection",
    "merge_collection",
]
